version: "3.8"

services:
  app:
    container_name: app-dev
    image: node:12-alpine
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000
